services:
  me:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: me
    environment:
      - ME_HOME=/app/me_data
      - ME_STATIC_DIR=/app/static
    ports:
      - "6868:6868"
    volumes:
      - ./me_data:/app/me_data
    restart: unless-stopped